services:
  - type: web
    name: butsoap-backend
    env: docker
    plan: free
    region: singapore
    branch: main
    rootDir: product_service
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
